### ISSUE TITLE
Stressed: Obj Export differences

### ISSUE THREAD

**Issue by LowLevelMahn** [dstien/gameformats#3]
Why ist the Obj File view different to the original view in Stressed?

![image](https://user-images.githubusercontent.com/580819/89763966-dd202180-daf3-11ea-813a-25a57ce9ec59.png)

the grid is missing, seem to be non polygona (the missing colors could be Meshlabs fault)

**Comment by dstien** [comment]
I haven't used MeshLab before, but after playing around with it it appears that it defaults to using vertex color, while the files exported from stressed has materials set by face:

![image](https://user-images.githubusercontent.com/118539/89796840-70744980-db2a-11ea-8cec-c2b840d677de.png)

As for the missing grid I'm not sure. I suspect that MeshLab can't import or show the line primitive. It's used by the obj format by simply referencing two vertices per segment:
```
l   3   9
l   4   9
l   8  10
l   7  10
```

**Comment by LowLevelMahn** [comment]
do you know a obj viewer that shows the model correct?

i tried Blender and some other online viewer - i can't see the grid
