### ISSUE TITLE
stunpack will not compile using gcc under cygwin

### ISSUE THREAD

**Issue by PeterSwinkels** [dstien/gameformats#6]
See the following output:

$ gcc stunpack.c main.c stunpack.h
In file included from main.c:26:
stunpack.h:89:13: warning: inline function ‘stpk_getLength’ declared but never defined
   89 | inline void stpk_getLength(stpk_Buffer *buf, uint *len);
      |             ^~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccf6pPrE.o:main.c:(.bss+0x0): multiple definition of `stpk_b16'; /tmp/ccvOGvVQ.o:stunpack.c:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccvOGvVQ.o:stunpack.c:(.text+0x8e): undefined reference to `stpk_getLength'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccvOGvVQ.o:stunpack.c:(.text+0x272): undefined reference to `stpk_getLength'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: /tmp/ccvOGvVQ.o:stunpack.c:(.text+0x530): undefined reference to `stpk_getLength'
collect2: error: ld returned 1 exit status

What am I doing wrong?

**Comment by duplode** [comment]
> What am I doing wrong?

Most likely nothing, @PeterSwinkels -- this looks like the issue mentioned at #5 . While I haven't managed to have a closer look at it yet, the patch suggested there by LowLevelMahn was enough for me to build Stressed in my system (Arch Linux, recent gcc) a few weeks ago, at least. The fix for Stunpack should be analogous.

**Comment by PeterSwinkels** [comment]
I got it to work in Visual Studio after removing the code for handling command line arguments. Hardcoding the options works for my purposes. I am trying to convert it to vb. It almost works now, but not quite.

Peter Swinkels

On 9 Mar 2023, at 00:06, Daniel Mlot ***@***.***> wrote:

﻿

What am I doing wrong?

Most likely nothing, @PeterSwinkels<https://github.com/PeterSwinkels> -- this looks like the issue mentioned at #5<https://github.com/dstien/gameformats/issues/5> . While I haven't managed to have a closer look at it yet, the patch suggested there by LowLevelMahn was enough for me to build it in my system (Arch Linux, recent gcc) a few weeks ago, at least.

**Comment by duplode** [comment]
> Hardcoding the options works for my purposes. I am trying to convert it to vb. It almost works now, but not quite.

Nice! Let us know if you need anything on the Stunts internals side of things.

**Comment by alex-286** [comment]
Hi, the build errors should be fixed by my dosbuild patch https://github.com/alex-286/gameformats/commit/7b13b7efa1ea6433562472396c0787d11b9c16df. I already created a pull request for this repo.

**Comment by PeterSwinkels** [comment]
Glad to hear it. I got it to work in Visual Studio btw. I had to remove the command-line parsing part though.

________________________________

**Comment by dstien** [comment]
Fixed in #8.
