### ISSUE TITLE
Does Stunpack need more documentation?

### ISSUE THREAD

**Issue by PeterSwinkels** [dstien/gameformats#7]
While Stunpack appears to decompress files well and provides a lot of useful output in verbose mode and the code is fairly well written it is hard to infer the format of the data being decompressed from the code. If the program's purpose is not to simply provide a method of decompressing files but also a means to assist people in understanding how these compressed files work, additional documentation should be provided describing their format.

**Comment by duplode** [comment]
You're right of course. Adding a proper description of the compression algorithm to the Stunts Wiki has been a pending task for years now; thanks for reminding me of it. I'll post any news on that front here.

**Comment by PeterSwinkels** [comment]
Glad to hear that. Btw, at the moment I am trying to rewrite your program in C instead of vb (failed twice). I am figuring it out the slow and hard way atm. It's a fun but hard challenge. 🙂
________________________________

**Comment by duplode** [comment]
Just for the sake of proper credit, Stunpack is 100% dstien's code. While I have made a few patches for Stressed, my contributions were mainly with documentation and testing. So I'll have to study the code a bit as well :)

**Comment by PeterSwinkels** [comment]
Indeed Stunpack is 100% by dstien. I wish you luck further developing Stunpack dstien!

**Comment by duplode** [comment]
That's a great [Wiki article](https://wiki.stunts.hu/wiki/Compression) — thanks a lot, @dstien !
